<?xml version="1.0" encoding="UTF-8"?>
<!-- 声明内部DTD -->
<!DOCTYPE scores [
        <!ELEMENT scores (student+)>
        <!ELEMENT student (name,course,score)>
        <!ATTLIST student id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT course (#PCDATA)>
        <!ELEMENT score (#PCDATA)>
        ]>
<scores>
    <student id="1">
        <name>王同</name>
        <course>java</course>
        <score>89</score>
    </student>
    <student id="2">
        <name>李佳</name>
        <course>sql</course>
        <score>58</score>
    </student>
    <student id="3">
        <name>王二狗</name>
        <course>经济学原理</course>
        <score>88</score>
    </student>
    <student id="4">
        <name>刘德华</name>
        <course>怎样做一个好演员</course>
        <score>100</score>
    </student>
</scores>
